#ifndef MIRMINCE_OSDEP_MIDNIGHTBSD_ASM_H
#define MIRMINCE_OSDEP_MIDNIGHTBSD_ASM_H

#define SYSCALLVB		SYSCALLB
#define SYSCALL0B		SYSCALLB
#define SYSCALL1B		SYSCALLB
#define SYSCALL2B		SYSCALLB
#define SYSCALL3B		SYSCALLB
#define SYSCALL4B		SYSCALLB
#define SYSCALL5B		SYSCALLB
#define SYSCALL6B		SYSCALLB
#define SYSCALLVD		SYSCALLD
#define SYSCALL0D		SYSCALLD
#define SYSCALL1D		SYSCALLD
#define SYSCALL2D		SYSCALLD
#define SYSCALL3D		SYSCALLD
#define SYSCALL4D		SYSCALLD
#define SYSCALL5D		SYSCALLD
#define SYSCALL6D		SYSCALLD

#define MIRMINCE_UT_MODE_T	mirmince_u16

#endif
