#!/bin/sh
# /home/tg/Misc/git/mirsol.git/mir/push-music
# on the git server - not to be run on a client

wk=/home/tg/Misc/.mirsol
set -x
set -e
cd "$(dirname "$0")/.."
test -n "$1" || GIT_WORK_TREE="$wk" git clean -dfx
test -z "$1" || printf '\n%s%s=%s\001\n' 'THE_' 'WORKTREE' "$wk"
exit 0
